config/routes.rb
Rails.application.routes.draw do

WorshipTogether::Application.routes.draw do
  root 'users#index'

  resources :users
  resources :rides
  resources :churches
  resources :services

  get 'login', to: 'logins#new', as: :login
  post 'login', to: 'logins#create', as: :logins
  delete 'logout', to: 'logins#destroy', as: :logout

     end
end

app/models/church.rb
class Church < ActiveRecord::Base
  belongs_to :user
  has_many :services
  has_many :users
  
  validates :user_id, presence: true
end

app/models/locking_example.rb
class LockingExample < ActiveRecord::Base
end

app/models/ride.rb
class Ride < ActiveRecord::Base
  belongs_to :user
  belongs_to :service
  has_many :user_rides
  has_many :users, through: :user_rides
  
  validates :user_id, presence: true
  validates :service_id, presence: true
end

app/models/service.rb
class Service < ActiveRecord::Base
  belongs_to :church
  has_many :rides

  validates :church, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :rides_provided, class_name: 'Ride', foreign_key: 'user_id'
  has_many :user_rides
  has_many :rides, through: :user_rides

  has_one :church
  # if the church profile manager doesn't attend that church, use:
  #    has_one :church_managed, class_name: 'Church', foreign_key: 'user_id'

  has_secure_password

  validates :name, presence: true,
  format: { with: /\A.{0,50}\z/}
  validates :email,
  presence: true,
  format: { with: /\A         # begin of input
                    [-\w+.]+   # dash, wordy, plus, or dot characters
                    @          # required at sign
                    [-a-z\d.]+ # dash, letter, digit, or dot chars
                    \z         # end of input
                    /xi }
  validates :password, presence: true
end

app/models/user_ride.rb
class UserRide < ActiveRecord::Base
  belongs_to :user
  belongs_to :ride
  
  validates :user_id, presence: true
  validates :ride_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  include LoginsHelper
end

app/controllers/churches_controller.rb
class ChurchesController < ApplicationController
  def index
    @churches = Church.all
  end

  def new
    @church = Church.new
  end

  def show
    @church = Church.find(params[:id])
  rescue
    flash[:danger] = "Unable to find church"
    redirect_to churches_path
  end
 end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_action :check_for_session, only: [:new]
  
  def new
  end

  def create
    user = User.find_by(name: params[:username])
    if user && user.authenticate(params[:password])
      flash[:success] = 'Logged in'
      session[:user_id] = user.id
      redirect_to users_path
    else
      flash.now[:danger] = 'Invalid username or password'
      render 'new'
    end
  end

  def destroy
    flash[:info] = 'Logged out'
    session[:user_id] = nil
    redirect_to users_path
  end
  
  def check_for_session
    if session[:user_id] != nil
      redirect_to users_path
      flash[:danger] = 'You are already logged in'
    end
  end
end

app/controllers/rides_controller.rb
class RidesController < ApplicationController
  def index
    order_param = (params[:order] || :Date).to_sym
    ordering = case order_param
    when :Date
      :date
    when :Service
      :service_id
    end
    @rides = Ride.order(ordering)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  
  def index
    order_param = (params[:order] || :Day).to_sym
    ordering = case order_param
    when :Time
      :start_time
    when :Day
      :day_of_week
    end
    days = ["Sunday", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", nil]
    if ordering == :start_time
      @services = Service.order(ordering)
    else
      @services = Service.all.sort_by {|s| days.index(s.day_of_week)}
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :ensure_user_logged_in, only: [:edit, :update, :destroy]
  before_action :ensure_correct_user, only: [:edit, :update]
  before_action :ensure_admin, only: [:destroy]
  before_action :ensure_user_not_logged_in, only: [:new, :create]
  before_action :check_for_self_deletion, only: [:destroy]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the site, #{@user.name}"
      redirect_to @user
    else
      flash.now[:danger] = "Unable to create new user"
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
  rescue
    flash[:danger] = "Unable to find user"
    redirect_to users_path
  end

  def edit
    @user = User.find(params[:id]) 
  end

  def update
    @user = User.find(params[:id]) 
    if @user.update_attributes(user_params)
      flash[:success] = "Information updated successfully."
      redirect_to(user_path)
    else
      flash[:danger] = "Something went wrong"
    end
  end

  def destroy
    @user = User.find(params[:id]) 
    @user.destroy
    flash[:success] = "User deleted successfully"
    redirect_to(users_path)

  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def ensure_user_logged_in
    unless current_user
      flash[:warning] = 'Not logged in'
      redirect_to login_path
    end
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless current_user?(@user)
      flash[:danger] = "Cannot edit other user's profiles"
      redirect_to root_path
    end
  rescue
    flash[:danger] = "Unable to find user"
    redirect_to users_path
  end

  def ensure_admin
    unless current_user.admin?
      flash[:danger] = 'Only admins allowed to delete users'
      redirect_to root_path
    end
  end

  def ensure_user_not_logged_in
    if current_user
      redirect_to root_path
      flash[:warning] = 'Logged in users cannot do that'
    end
  end

  def check_for_self_deletion
    @user = User.find(params[:id]) 
    if current_user?(@user)
      flash[:danger] = "You deleted yourself"
      redirect_to(root_path)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/churches_helper.rb
module ChurchesHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
    def current_user
	User.find(session[:user_id]) if session[:user_id]
    end

    def current_user?(user)
	current_user == user
    end

    def logged_in?
	session[:user_id]
    end
end

app/helpers/rides_helper.rb
module RidesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/churches/_church.html.erb
<li>
  <%= link_to church.name, church, method: :show %>
</li>

app/views/churches/index.html.erb
<h1>List of churches</h1>

<p><%= pluralize(@churches.count, 'church') %></p>
<ol><%= render @churches %></ol>

app/views/churches/show.html.erb
<h1>Profile Page for <%= @church.name %></h1>

<p><%= link_to 'official web site', @church.web_site.to_s %></p>

<p> <%= image_tag @church.picture %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WorshipTogether</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class = 'main container'>

      <nav role="navigation" class="navbar navbar-default">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class='navbar-brand'><%=link_to 'Worship Together', root_path %></div>
        </div>
        <!-- Collection of nav links and other content for toggling -->
        <div id="navbarCollapse" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <!-- <li class="active"><a href="#">Home</a></li>
<li><a href="#">Profile</a></li>
<li><a href="#">Messages</a></li> -->
            <li><%= link_to 'Users', users_path %></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if logged_in? %>
            <li><%= link_to 'Log Out', logout_path, method: :delete %></li>
            <% else %>
            <li><%= link_to 'Sign Up', new_user_path %></li>
            <li><%= link_to 'Log In', login_path %></li>
            <% end %>
          </ul>
        </div>
      </nav>  

      <!-- <nav>
<ul>
<% if logged_in? %>
<li><%= link_to 'Log Out', logout_path, method: :delete %></li>
<% else %>
<li><%= link_to 'Log In', login_path %></li>
<% end %>
</ul>
</nav> -->

      <% flash.each do |type, message| %>
      <p class="alert alert-<%= type %>"><%= message %></p>
      <% end %>

      <%= yield %>
    </div>
  </body>
</html>

app/views/logins/new.html.erb
<h1>Sign In</h1>

<%= form_tag logins_path do %>
    <%= label_tag :username %>
    <%= text_field_tag :username, params[:username] %>

    <%= label_tag :password %>
    <%= password_field_tag :password, params[:password] %>

    <%= submit_tag 'Log In' %>
<% end %>

app/views/rides/_ride.html.erb
<li>
    <ul>
	<li>From: <%= link_to ride.user.name, ride.user %></li>
	<li>To: <%= ride.service.church.name %></li>
	<li>Service: <%= ride.service.location %> @ <%= ride.service.start_time %></li>
	<li>Date: <%= ride.date %>
	<li><%= link_to 'Ride details', ride %></li>
    </ul>
</li>

app/views/rides/index.html.erb
<h1>List of rides</h1>

<p><%= pluralize(@rides.count, 'ride') %></p>
<ol><%= render @rides %></ol>

app/views/services/_service.html.erb
<li>
  <ul>
    <li>Church: <%= Church.find(service.church_id).name %></li>
    <li>Time: <%= service.start_time %> to <%= service.finish_time %></li>
    <li>Day of the week: <%= service.day_of_week %></li>
    <li>Meeting location: <%= service.location %>
  </ul>
</li>

app/views/services/index.html.erb
<h1>List of services</h1>

<p><%= pluralize(@services.count, 'service') %></p>
<ol><%= render @services %></ol>

app/views/users/_errors.html.erb
<% if @user.errors.any? %>
    <p class="alert alert-danger">The form has <%= pluralize(@user.errors.count, 'error') %>.</p>
    <ul>
	<% @user.errors.full_messages.each do |message| %>
	    <li><%= message %></li>
	<% end %>
    </ul>
<% end %>

app/views/users/_fields.html.erb
<%= f.label :name, 'Username' %>
<%= f.text_field :name %>

<%= f.label :email %>
<%= f.text_field :email %>

<%= f.label :password %>
<%= f.password_field :password %>

<%= f.label :password_confirmation, 'Confirmation' %>
<%= f.password_field :password_confirmation %>

app/views/users/_user.html.erb
<li>
    <%= user.name %>: <%= user.email %>
    <%= link_to 'delete', user, method: :delete %>
</li>

app/views/users/edit.html.erb
<h1>Edit profile</h1>

<%= render partial: 'errors' %>

<%= form_for @user do |form| %>
    <%= render partial: 'fields', locals: { f: form } %>

<%= form.submit 'Update user profile' %>
<% end %>

app/views/users/index.html.erb
<h1>List of users</h1>

<p><%= pluralize(@users.count, 'user') %></p>
<ol><%= render @users %></ol>

app/views/users/new.html.erb
<%= render partial: 'errors' %>

<%= form_for @user do |form| %>
    <%= render partial: 'fields', locals: { f: form } %>

<%= form.submit 'Create new user' %>
<% end %>

app/views/users/show.html.erb
<h1>Profile Page for <%= @user.name %></h1>

<p>Email: <%= @user.email %></p>

app/views/users/update.html.erb
This is text